# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: HuBMAP dataset upload
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "/ingest-validation-tools" # the subpath of your site, e.g. /blog
url: "https://hubmapconsortium.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
categories-order:
 - Organ
 - Sample
 - Clinical Imaging Modalities
 - Fluorescence In Situ Hybridization (FISH)
 - Histology
 - Imaging Mass Spectrometry (IMS)
 - Mass Spectrometry
 - Multiplex Fluorescence Based Experiment (MxFBE)
 - Sequence Assays
 - Single-cycle Fluorescence Microscopy (SFM)
 - Spatial Transcriptomics
 - Other TSVs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
